arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1: {p: 2000.0, i: 0.01, d: 0.1}
    arm_joint_2: {p: 2000.0, i: 0.01, d: 0.1}
    arm_joint_3: {p: 2000.0, i: 0.01, d: 0.1}
    arm_joint_4: {p: 2000.0, i: 0.01, d: 0.1}
    arm_joint_5: {p: 2000.0, i: 0.01, d: 0.1}
  constraints:
    goal_time: 0.6
    arm_joint_1:
      goal: 0.1
    arm_joint_2:
      goal: 0.1
    arm_joint_3:
      goal: 0.1
    arm_joint_4:
      goal: 0.1
    arm_joint_5:
      goal: 0.1

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_finger_joint_l
    - gripper_finger_joint_r
  gains:
    gripper_finger_joint_l: {p: 40.0, d: 1.0}
    gripper_finger_joint_r: {p: 40.0, d: 1.0}

arm_joint1_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_joint_1
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint2_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_joint_2
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint3_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_joint_3
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint4_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_joint_4
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint5_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: arm_joint_5
  pid: {p: 2000.0, i: 0.01, d: 0.1}



arm_joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_1
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_2
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_3
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_4
  pid: {p: 2000.0, i: 0.01, d: 0.1}

arm_joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: arm_joint_5
  pid: {p: 2000.0, i: 0.01, d: 0.1}